#!/bin/sh

if [ "z${GIT_DEBUG}" != "z" ]; then
    set -x
fi

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Elixir
## format
EX_SRCS=$(git diff --cached --name-only --diff-filter=ACM --no-color | grep --color=never -e '\.ex\(\|s\)$')

if [ "z${EX_SRCS}" != "z" ]; then
    mix format.all
    for EX_FILE in "${EX_SRCS}"; do
        echo "${EX_FILE}" >> .commit
    done
fi

# GraphQL
## format
GQL_SRCS=$(git diff --cached --name-only --diff-filter=ACM --no-color | grep --color=never -e '\.gql$')

if [ "z${GQL_SRCS}" != "z" ]; then
    for GQL_FILE in ${GQL_SRCS}; do
        prettier --write "${GQL_FILE}"
        echo "${GQL_FILE}" >> .commit
    done
fi

# Elm
## format
ELM_SRCS=$(git diff --cached --name-only --diff-filter=ACM --no-color | grep --color=never -e '\.elm$')

if [ "z${ELM_SRCS}" != "z" ]; then
    for ELM_FILE in ${ELM_SRCS}; do
        elm-format --yes "${ELM_FILE}"
        echo "${ELM_FILE}" >> .commit
    done
fi
