#!/bin/sh

if [ "z${GIT_DEBUG}" != "z" ]; then
    set -x
else
    # Redirect output to stderr
    2>&1
fi

z40=0000000000000000000000000000000000000000
changed_files=""
while read local_ref local_sha remote_ref remote_sha
do
    if [ "$local_sha" != $z40 ]; then
        if [ "$remote_sha" = $z40 ]; then
            ### Pushing a new branch or on a new remote
            exit 0
        fi
        local_commits=$(git rev-list "$remote_sha...$local_sha")
        for commit in $local_commits
        do
            for file_ in $(git diff-tree --no-commit-id --name-only -r $commit)
            do
                changed_files+="${file_}"
            done
        done
    fi
done

# Elixir
if echo -e $changed_files|grep --color=never -e '\.ex\(\|s\)$' > /dev/null; then
    if docker-compose ps|grep Up|grep -v Exit > /dev/null; then
        compose_was_up=1
    fi
    docker-compose up -d

    ## Run tests
    docker-compose run web mix test
    if [ "$?" -ne 0 ]; then
        echo "TESTS FAILED!"
        exit 1
    fi

    ## Run checks
    docker-compose run web mix check
    if [ "$?" -ne 0 ]; then
        echo "CHECKS FAILED!"
        exit 2
    fi

    if [ -z ${compose_was_up} ]; then
        docker-compose stop
    fi
fi

# Elm
if echo -e $changed_files|grep --color=never -e '\.elm$' > /dev/null; then
    ## analyse
    cwd="${PWD}"
    cd assets/
    elm-analyse
    if [ $? -ne 0 ]; then
        echo "elm-analyse FAILED!"
        exit 3
    fi
    cd "${cwd}"
fi
